// Generate the FriendSDK v0.1.2 "Friend Edition" game module from the standalone sources.
// Output (inside the SDK game folder, which `friendsdk check` requires):
//   sdk/games/rare-heist/heist.generated.js   ESM: export boot(root, options), readFriend(friendId)
//   sdk/games/rare-heist/heist.generated.d.ts types for the adapter
//   sdk/games/rare-heist/heist.generated.css  src/style.css, verbatim
// The standalone index.html (build.mjs) is not affected. `--verify` fails if the outputs are stale.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const root=path.dirname(fileURLToPath(import.meta.url));
const at=(...p)=>path.join(root,...p);
const gameDir=at('sdk','games','rare-heist');
// Line endings are normalised so the output is identical on every checkout (core.autocrlf).
const text=async file=>(await readFile(file,'utf8')).replace(/\r\n/g,'\n');

// Pure game modules plus the UI. Not bundled: art.js (guest sample Friends), burn.js (LIVE BURN),
// street.js (walking hub), last-heist.js / last-client.js (shared server mode).
const LIBRARIES=['pixel-font.js','engine.js','economy.js','identity.js','cutaway-rules.js','cutaway-levels.js','solutions.js','cutaway-render.js','playfeel.js'];
// Elements of the standalone shell that ui.js only touches outside Friend Edition (guarded by `SDK`).
const STANDALONE_ONLY=new Set(['wallet','friend','homeWallet','about','storageWarning','streetCanvas','doorName','doorDesc','enterDoor','districtTabs','streetProgress',
 'editorTitle','editStatus','palette','editNameLabel','editName','editX','editY','editDir','editPeriod','editPhase','editCircuit','initialLightLabel','editLight',
 'placeTool','editUndo','testRoom','publishRoom','newRoom']);
// Controls that must never exist in the sandboxed edition's markup.
const FORBIDDEN_IDS=['wallet','friend','homeWallet','about','publishRoom','importJob','resultCard','resultRemix','lvConnect','raidShared','invite','walletConnect','previewRead','inspectRead'];

const ui=await text(at('src','ui.js'));
const shell=await text(at('src','shell.html'));
let markup=(await text(at('sdk','src','friend-shell.html'))).replace(/^<!--[\s\S]*?-->\s*/,'').trim();
const glue=(await text(at('sdk','src','friend-edition.js'))).trim();
const css=await text(at('src','style.css'));

// Every static element ui.js looks up must exist in the SDK markup or be declared standalone-only.
const ids=new Set([...markup.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]));
const used=new Set([...ui.matchAll(/\$\('([A-Za-z0-9_-]+)'\)/g)].map(m=>m[1]));
const shellIds=new Set([...shell.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]));
const missing=[...used].filter(id=>shellIds.has(id)&&!ids.has(id)&&!STANDALONE_ONLY.has(id));
if(missing.length)throw Error('SDK markup lacks elements used by ui.js: '+missing.join(', ')+'. Add them to sdk/src/friend-shell.html or guard them in ui.js.');
const leaked=FORBIDDEN_IDS.filter(id=>ids.has(id));
if(leaked.length)throw Error('SDK markup must not contain: '+leaked.join(', '));
for(const page of ['street','catalog','last','replays','studio','play'])if(!ids.has(page+'Page'))throw Error('SDK markup lacks #'+page+'Page (ui.js show()).');
if(!/const SDK=globalThis\.RareHeistSDK\|\|null;/.test(ui))throw Error('ui.js lacks the SDK flag.');

const sources=[];
for(const name of LIBRARIES)sources.push('// ---- src/'+name+' ----\n'+(await text(at('src',name))).trim());
const inputs=createHash('sha256');
for(const part of [markup,glue,ui,css,...sources])inputs.update(part);

const js=`// GENERATED by publish/rare-heist/build-sdk.mjs. Do not edit; change src/ or sdk/src/ and regenerate.
// Rare Heist: Friend Edition for FriendSDK v0.1.2 (sandboxed game frame). Inputs sha256 ${inputs.digest('hex').slice(0,16)}.
// Sources: src/{${LIBRARIES.map(n=>n.replace(/\.js$/,'')).join(',')},ui}.js, sdk/src/friend-shell.html, sdk/src/friend-edition.js.
/* eslint-disable */
const MARKUP=${JSON.stringify(markup)};
let loaded=false,instance=null;

function loadLibraries(){
 if(loaded)return;
 loaded=true;
 // The sources are browser/CommonJS modules; these locals select their browser branch.
 const module=undefined,exports=undefined,require=undefined;
${sources.join('\n')}
 // ---- Friend Edition: read-only artwork subset of HeistIdentity (no wallet functions) ----
 const identity=globalThis.HeistIdentity;
 globalThis.HeistIdentity=Object.freeze({MANIFEST:identity.MANIFEST,FAMILIES:identity.FAMILIES,token:identity.token,short:identity.short,formatRF:identity.formatRF,sample:identity.sample,preview:identity.preview});
 // ---- Friend Edition: inert stand-ins for standalone-only modules that are not bundled ----
 globalThis.RF_ART=[];
 globalThis.HeistBurn=Object.freeze({byId:()=>null,unlocked:()=>[]});
 globalThis.LastHeist=Object.freeze({});
}

// ---- sdk/src/friend-edition.js ----
${glue}

/** Read the selected Friend's canonical 16x16 one-bit frames (familyOf, seedOf, frames) via the public RPC. */
export async function readFriend(friendId,options={}){
 loadLibraries();
 return (await globalThis.HeistIdentity.preview(String(friendId),options)).sample;
}

/** Mount the game into root: once per document. options: {friendId, hero, paused: () => boolean, mode}. */
export function boot(root,options){
 loadLibraries();
 if(instance){
  if(instance.friendId!==String(options.friendId))throw new Error('This game frame already belongs to Friend #'+instance.friendId+'. Reload the game to switch Friends.');
  if(instance.app.parentNode!==root)root.appendChild(instance.app);
  instance.update(options);
  return instance;
 }
 const sdk=createFriendEdition(root,options,MARKUP);
 instance=sdk;
 // ---- src/ui.js ----
${ui.trim()}
 return sdk;
}
`;
const generatedCss='/* GENERATED by publish/rare-heist/build-sdk.mjs from src/style.css. Do not edit. */\n'+css.trim()+'\n';

const types=`// GENERATED by publish/rare-heist/build-sdk.mjs. Types for heist.generated.js.
/** One Friend's canonical artwork: 64 one-bit 16x16 frames (256-bit hex words) and their clips. */
export type FriendSample = { tokenId: string; familyId: number; family: string; familyName: string; seed: number; frames: string[]; clips: Record<string, number[]> };
export type BootOptions = { friendId: string; hero: FriendSample; paused: () => boolean; mode?: "preview" | "chain" };
export declare function readFriend(friendId: bigint | string, options?: { timeout?: number }): Promise<FriendSample>;
export declare function boot(root: HTMLElement, options: BootOptions): { friendId: string; app: HTMLElement };
`;
const outputs=[[path.join(gameDir,'heist.generated.js'),js],[path.join(gameDir,'heist.generated.d.ts'),types],[path.join(gameDir,'heist.generated.css'),generatedCss]];
if(process.argv.includes('--verify')){
 const stale=[];
 for(const [file,body] of outputs){let old='';try{old=(await readFile(file,'utf8')).replace(/\r\n/g,'\n');}catch{}if(old!==body)stale.push(path.relative(root,file));}
 if(stale.length){console.error('Stale generated files: '+stale.join(', ')+'. Run: node build-sdk.mjs');process.exit(1);}
 console.log('Generated Friend Edition files are current.');
}else{
 for(const [file,body] of outputs)await writeFile(file,body);
 console.log('Built '+outputs.map(([f,b])=>path.relative(root,f)+' ('+Buffer.byteLength(b)+' bytes)').join(', '));
}
