// src/solutions.js (generated by scripts/gen-solutions.mjs) must match the shipped plans: every level has a stored route
// and it still wins cleanly with the current engine. A level edit without regenerating the routes fails here.
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine.js'),C=require('../src/cutaway-rules.js'),A=require('../src/last-heist.js');
const levels=require('../src/cutaway-levels.js'),SOL=require('../src/solutions.js');

test('every shipped plan has a stored solution, and no stale ones remain',()=>{
 const ids=levels.map(l=>l.id);
 assert.deepEqual(ids.filter(id=>!SOL[id]),[],'missing: run node scripts/gen-solutions.mjs');
 assert.deepEqual(Object.keys(SOL).filter(id=>!ids.includes(id)),[],'stale: run node scripts/gen-solutions.mjs');
});
for(const l of levels)test('stored solution for '+l.id+' wins cleanly with the current engine',()=>{
 const s=SOL[l.id],q=E.replay(C.normalize(l),s.actions,'ghost');
 assert.equal(q.ok,true,l.id+' route no longer wins: regenerate src/solutions.js');
 assert.equal(q.state.empUsed,0);assert.equal(q.state.alarms,0);assert.equal(s.turns,s.actions.length);
 assert.ok(s.actions.every(a=>E.ACTIONS.includes(a)&&a!=='EMP'));
});
test('the Last Heist opening vault route passes the server rules (HOUSE RUN)',()=>{
 assert.doesNotThrow(()=>A.validateLog(A.seed(),SOL['last-cutaway'].actions));
});
// Daily Heist: every plan in src/daily-levels.js has a stored route in src/daily-solutions.js that wins cleanly.
test('every Daily Heist plan has a stored clean winning route',()=>{
 const daily=require('../src/daily-levels.js'),DSOL=require('../src/daily-solutions.js');
 assert.deepEqual(Object.keys(DSOL).sort(),daily.map(l=>l.id).sort(),'run node scripts/gen-solutions.mjs');
 for(const l of daily){const s=DSOL[l.id],q=E.replay(C.normalize(l),s.actions,'ghost');
  assert.equal(q.ok,true,l.id+' route no longer wins');assert.equal(q.state.empUsed,0,l.id);assert.equal(q.state.alarms,0,l.id);
  assert.equal(s.turns,s.actions.length,l.id);assert.ok(s.turns>=l.best&&s.turns<=l.par,l.id+' route between best and PAR');}
});
