// Copy the existing presentation and inject platform hooks into this edition only.
// Never edits the standalone sources or Friend Edition v0.1.4.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const directory = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(directory, '..');
const read = async name => (await readFile(path.join(source, name), 'utf8')).replace(/\r\n/g, '\n');
const write = (name, value) => writeFile(path.join(directory, name), value);
const modules = ['pixel-font', 'engine', 'economy', 'identity', 'cutaway-rules', 'cutaway-levels', 'solutions', 'cutaway-render', 'playfeel'];
const libraries = await Promise.all(modules.map(name => read('src/' + name + '.js')));
const pure = ['engine', 'cutaway-rules', 'cutaway-levels', 'playfeel', 'daily-levels'];
const rules = await Promise.all(pure.map(name => read('src/' + name + '.js')));
await write('rules.generated.js', '// Generated pure game rules for browser + Nakama.\n' +
  'const scope={};\n(function(globalThis){const module=undefined,exports=undefined,require=undefined;\n' + rules.join('\n') +
  '\n})(scope);\nexport const engine=scope.HeistEngine, cutaway=scope.CutawayRules, plans=scope.HEIST_CUTAWAY_LEVELS, feel=scope.HeistPlayfeel, daily=scope.HEIST_DAILY_LEVELS;\n');
let ui = await read('src/ui.js');
function replace(before, after) {
  if (!ui.includes(before)) throw Error('Platform generator anchor changed: ' + before);
  ui = ui.replace(before, after);
}
replace("function read(key,max=1000000){try", "function read(key,max=1000000){if(SDK)return key===KEY?SDK.progress:null;try");
replace("function persist(){save.economy", "function persist(){SDK?.settings({sound:save.sound,reduced:save.reduced,theme:save.theme,trail:save.trail});save.economy");
replace("function sessionId(){try", "function sessionId(){if(SDK)return 'platform';try");
replace("function record(){if(game.recorded||game.shared||game.type==='test'||game.type==='fortify')return;", "function record(){if(game.recorded||game.shared||game.type==='test'||game.type==='fortify')return;SDK?.record({levelId:game.level.id,actions:[...game.actions],mode:game.state.mode,practice:game.practice});");
replace("const hasItem=id=>economy.owned.includes(id)||liveOwned().includes(id);", "const hasItem=id=>SDK?SDK.items.includes(id):economy.owned.includes(id)||liveOwned().includes(id);");
replace("if(!save.done.includes(game.level.id)){", "if(!game.practice&&!save.done.includes(game.level.id)){");
replace("Goals are saved on this device", "Goals are saved on your Friend by the game server");
let glue = await read('sdk/src/friend-edition.js');
glue = glue.replace("progress resets when the frame reloads.", "progress is stored by the game server.");
glue = glue.replace("Progress lasts for this session.", "Progress is stored on your Friend. Preview storage lasts only for this host session.");
glue = glue.replace("No purchases or rewards: the SDK economy is not used.", "Paid features await the platform module bridge; free practice awards no RF.");
glue = glue.replace("Progress lives in memory.", "Progress is loaded from Friend-scoped server rules.");
glue = glue.replace("attach(api) { ui = api; },", `progress: options.progress, items: options.items,
  settings(value) { options.settings(value); },
  record(value) { options.record(value); },
  attach(api) { ui = api; if(options.items.includes('archive-pack'))ui.jobs.push(...globalThis.HEIST_CUTAWAY_LEVELS.filter(l=>l.id.startsWith('archive-')).map(globalThis.CutawayRules.normalize)); },`);
glue = glue.replace("portraitFrame = 0; drawPortrait(); animatePortrait();", `options.extendLobby(page, ui); portraitFrame = 0; drawPortrait(); animatePortrait();`);
glue = glue.replace(/function about\(\) \{[\s\S]*?\n \}\n\n return sdk;/, `function about() {
  ui.modal('PLATFORM EDITION', '<p>FriendSDK v0.2.3. Progress is replay-validated by Friend-scoped server.ts. A Nakama backend makes it durable; local preview survives a game-frame reload but not a whole host reload.</p><p>Shop, Daily entry and Last Heist stakes need the official Draw/Round bridge. Free Daily archive and the fixed Last Heist plan are practice only.</p>');
 }
 return sdk;`);
const markup = (await read('sdk/src/friend-shell.html')).replace(/^<!--[\s\S]*?-->\s*/, '').replace(' / FRIEND EDITION', ' / PLATFORM');
await write('heist.generated.js', `// Generated by platform/generate.mjs; standalone UI remains untouched.
const MARKUP=${JSON.stringify(markup)};
let loaded=false,instance=null;
function loadLibraries(){if(loaded)return;loaded=true;const module=undefined,exports=undefined,require=undefined;
${libraries.join('\n')}
const identity=globalThis.HeistIdentity;
globalThis.HeistIdentity=Object.freeze({MANIFEST:identity.MANIFEST,FAMILIES:identity.FAMILIES,token:identity.token,short:identity.short,formatRF:identity.formatRF,sample:identity.sample,preview:identity.preview});
globalThis.RF_ART=[];globalThis.HeistBurn=Object.freeze({byId:()=>null,unlocked:()=>[]});globalThis.LastHeist=Object.freeze({});}
${glue}
export async function readFriend(friendId){loadLibraries();return (await globalThis.HeistIdentity.preview(String(friendId))).sample;}
export function boot(root,options){loadLibraries();if(instance){instance.update(options);return instance;}
const sdk=createFriendEdition(root,options,MARKUP);instance=sdk;
${ui}
return sdk;}
`);
await write('heist.generated.css', await read('src/style.css'));
await write('sdk.generated.css', (await read('sdk/games/rare-heist/sdk.css')) + '\n:root { --rh-band: 0px; }\n');
console.log('Generated platform edition and pure Nakama rules. No burn.js or standalone server included.');
