// GENERATED by publish/rare-heist/build-sdk.mjs. Types for heist.generated.js.
/** One Friend's canonical artwork: 64 one-bit 16x16 frames (256-bit hex words) and their clips. */
export type FriendSample = { tokenId: string; familyId: number; family: string; familyName: string; seed: number; frames: string[]; clips: Record<string, number[]> };
export type BootOptions = { friendId: string; hero: FriendSample; paused: () => boolean; mode?: "preview" | "chain" };
export declare function readFriend(friendId: bigint | string, options?: { timeout?: number }): Promise<FriendSample>;
export declare function boot(root: HTMLElement, options: BootOptions): { friendId: string; app: HTMLElement };
