/* GENERATED by scripts/gen-solutions.mjs from src/cutaway-levels.js with tests/solve.cjs. Do not edit by hand.
   One clean route per shipped plan (no EMP, ghost rules): a witness that the level can be cleared, not a shortest-path
   claim. tests/solutions.test.cjs replays every route with the current engine. 23 plans, longest 64 turns. */
(function(root){const solutions=Object.freeze({
 "cut-00":{"turns":18,"actions":["E","S","S","E","S","S","E","E","E","E","E","E","N","N","E","N","N","E"]},
 "cut-01":{"turns":46,"actions":["S","S","E","E","E","E","E","E","S","S","W","W","W","W","W","VENT","E","E","E","W","W","W","E","E","E","E","E","E","E","E","N","N","W","W","W","N","N","E","E","E","WAIT","E","E","N","N","E"]},
 "cut-02":{"turns":23,"actions":["E","S","S","N","WAIT","S","E","S","S","E","E","E","WAIT","WAIT","E","E","E","N","N","N","N","E","E"]},
 "cut-03":{"turns":30,"actions":["E","S","S","E","S","S","W","E","N","N","W","N","S","E","E","E","W","W","W","N","N","E","E","E","E","E","E","E","E","E"]},
 "cut-04":{"turns":57,"actions":["E","S","S","E","E","E","E","E","S","S","E","E","E","S","S","W","W","W","W","W","W","W","W","E","E","E","E","E","E","W","WAIT","E","E","E","N","N","W","W","W","W","W","W","W","W","E","E","E","E","E","N","N","E","N","N","E","E","E"]},
 "cut-05":{"turns":37,"actions":["E","E","S","S","E","E","S","S","W","W","E","E","E","E","E","E","E","W","W","W","W","W","N","WAIT","N","W","W","N","N","E","E","E","E","E","E","E","E"]},
 "cut-06":{"turns":34,"actions":["E","S","S","W","E","E","S","S","W","S","S","E","E","E","E","W","W","W","W","N","N","E","N","N","E","E","E","E","E","E","E","N","N","E"]},
 "cut-07":{"turns":44,"actions":["E","E","LIGHT","S","S","E","E","E","E","E","E","S","S","W","W","W","W","W","W","S","S","W","E","N","N","E","E","W","W","S","WAIT","N","E","E","E","E","E","E","N","N","E","N","N","E"]},
 "cut-08":{"turns":31,"actions":["E","S","S","VENT","E","E","E","E","E","WAIT","W","WAIT","E","E","E","N","N","S","WAIT","N","E","N","N","S","WAIT","N","W","N","N","E","E"]},
 "cut-09":{"turns":33,"actions":["E","S","S","W","E","E","S","WAIT","WAIT","WAIT","S","W","S","WAIT","S","N","WAIT","N","E","N","N","E","E","E","E","E","E","W","N","N","E","E","E"]},
 "cut-10":{"turns":64,"actions":["E","S","S","W","E","E","LIGHT","E","E","E","E","E","W","W","W","S","S","W","W","E","E","E","E","E","E","E","W","W","S","S","W","W","W","W","W","VENT","E","E","E","WAIT","E","E","E","E","N","N","W","N","N","W","W","W","N","N","E","E","E","E","E","N","N","E","E","E"]},
 "annex-01":{"turns":33,"actions":["E","S","LIGHT","S","E","S","S","W","S","S","N","N","E","E","E","E","E","E","E","N","N","W","W","W","W","E","E","N","N","E","E","E","E"]},
 "annex-02":{"turns":37,"actions":["E","S","S","E","S","S","W","S","S","N","N","E","N","N","E","E","W","WAIT","E","E","E","E","WAIT","S","WAIT","WAIT","S","W","E","N","WAIT","N","N","N","E","E","E"]},
 "cut-11":{"turns":50,"actions":["E","S","LIGHT","S","E","E","S","S","W","W","W","E","E","E","N","N","E","E","E","E","E","E","S","S","S","WAIT","WAIT","S","W","W","WAIT","WAIT","WAIT","W","E","WAIT","WAIT","WAIT","WAIT","E","E","N","N","N","N","N","N","E","E","E"]},
 "cut-12":{"turns":47,"actions":["E","S","S","E","E","S","S","WAIT","N","N","E","E","E","E","E","E","E","E","E","VENT","W","W","W","W","W","W","W","WAIT","WAIT","WAIT","W","E","E","E","E","N","WAIT","WAIT","N","E","N","N","E","N","N","E","E"]},
 "archive-01":{"turns":52,"actions":["E","E","E","E","S","S","W","W","E","E","E","E","E","S","S","E","E","W","W","W","W","W","W","S","S","E","E","WAIT","WAIT","E","W","W","W","N","N","E","E","E","E","N","N","W","W","W","N","N","E","E","E","E","E","E"]},
 "archive-02":{"turns":50,"actions":["E","S","S","E","E","LIGHT","E","E","E","E","E","S","S","WAIT","N","WAIT","WAIT","S","W","W","S","WAIT","WAIT","N","W","W","W","W","W","S","S","N","N","E","E","E","E","E","S","WAIT","WAIT","N","E","E","N","N","E","N","N","E"]},
 "archive-03":{"turns":43,"actions":["E","S","S","E","S","S","E","E","W","W","N","N","E","E","W","W","W","VENT","WAIT","WAIT","WAIT","E","E","E","E","E","E","E","E","N","N","S","WAIT","N","W","N","N","W","N","N","E","E","E"]},
 "drill-pulse":{"turns":20,"actions":["E","S","S","S","S","E","E","WAIT","WAIT","WAIT","WAIT","E","E","E","E","N","N","N","N","E"]},
 "drill-light":{"turns":23,"actions":["E","S","LIGHT","S","E","S","S","E","E","W","W","N","N","W","N","N","E","E","E","E","E","E","E"]},
 "drill-weight":{"turns":36,"actions":["E","S","S","S","S","E","E","W","W","N","N","E","E","E","E","S","S","E","E","W","W","N","N","W","W","W","W","N","N","E","E","E","E","E","E","E"]},
 "drill-walker":{"turns":29,"actions":["E","S","S","E","E","E","S","S","W","W","W","E","E","E","N","WAIT","N","WAIT","S","WAIT","WAIT","WAIT","N","E","E","E","N","N","E"]},
 "last-cutaway":{"turns":30,"actions":["E","N","N","E","E","N","N","W","W","N","N","E","E","W","W","S","S","E","E","S","S","E","E","E","E","S","S","E","E","E"]}
});if(typeof module==='object'&&module.exports)module.exports=solutions;else root.HEIST_SOLUTIONS=solutions;})(globalThis);
